export const categoryImages = [
    { value: 'car_insurance.png', label: 'Car Insurance' },
    { value: 'car_loan_repayment.png', label: 'Car Loan Repayment' },
    { value: 'car_repayment.png', label: 'Car Repayment' },
    {
        value: 'car_repairs_and_maintenance.png',
        label: 'Car Repairs & Maintenance',
    },
    { value: 'creditcard_downpayment.png', label: 'Credit Card Paydown' },
    { value: 'daily_expenses.png', label: 'Daily Expenses' },
    { value: 'deposits.png', label: 'Deposits' },
    { value: 'dog.png', label: 'Dog' },
    { value: 'entertainment.png', label: 'Entertainment' },
    { value: 'family.png', label: 'Family' },
    { value: 'gas.png', label: 'Gas' },
    { value: 'gifts.png', label: 'Gifts' },
    { value: 'groceries.png', label: 'Groceries' },
    { value: 'home_repairs.png', label: 'Home Repairs' },
    { value: 'home.png', label: 'Household' },
    { value: 'household_supplies.png', label: 'Household Supplies' },
    { value: 'income_pool.png', label: 'Income Pool' },
    { value: 'ira_loan.png', label: 'IRA Loan' },
    { value: 'medical_and_health.png', label: 'Medical and Health' },
    { value: 'money.png', label: 'Money' },
    { value: 'outings_and_eating_out.png', label: 'Outings and Eating Out' },
    { value: 'overdraft_fees.png', label: 'Overdraft Fees' },
    { value: 'parking_and_tolls.png', label: 'Parking & Tolls' },
    { value: 'personal.png', label: 'Personal' },
    { value: 'personal_expenses.png', label: 'Personal Spending' },
    { value: 'online_services.png', label: 'Subscriptions and Online Services' },
    { value: 'tithe.png', label: 'Tithe' },
    { value: 'transfers.png', label: 'Transfers' },
    { value: 'transport.png', label: 'Transportation' },
    { value: 'utilities.png', label: 'Utilities' },
    { value: 'vacation_and_travel.png', label: 'Vacation and Travel' },
];
