import {
    Baby,
    Banknote,
    Bike,
    Briefcase,
    Car,
    CircleDollarSign,
    Coffee,
    CreditCard,
    Dog,
    Dumbbell,
    Gift,
    GraduationCap,
    HandHeart,
    Heart,
    Home,
    Landmark,
    Laptop,
    Plane,
    PiggyBank,
    Receipt,
    Shirt,
    ShoppingCart,
    Smartphone,
    Sparkles,
    Stethoscope,
    User,
    Users,
    Utensils,
    WalletCards,
    Wrench,
} from '@lucide/vue';

export const categoryIcons = {
    baby: Baby,
    banknote: Banknote,
    bike: Bike,
    briefcase: Briefcase,
    car: Car,
    'circle-dollar-sign': CircleDollarSign,
    coffee: Coffee,
    'credit-card': CreditCard,
    dog: Dog,
    dumbbell: Dumbbell,
    gift: Gift,
    'graduation-cap': GraduationCap,
    'hand-heart': HandHeart,
    heart: Heart,
    home: Home,
    landmark: Landmark,
    laptop: Laptop,
    plane: Plane,
    'piggy-bank': PiggyBank,
    receipt: Receipt,
    shirt: Shirt,
    'shopping-cart': ShoppingCart,
    smartphone: Smartphone,
    sparkles: Sparkles,
    stethoscope: Stethoscope,
    user: User,
    users: Users,
    utensils: Utensils,
    'wallet-cards': WalletCards,
    wrench: Wrench,
};

export const categoryIconOptions = Object.entries(categoryIcons).map(
    ([value, icon]) => ({
        value,
        icon,
    }),
);

export type CategoryIconName = keyof typeof categoryIcons;
